# config.yml

# Preprocessing Parameters
preprocess_chunksize: 100000  # Adjust based on system memory
preprocess_fillna_method: ffill  # Options: 'ffill', 'bfill'

# Feature Engineering Parameters
feature_engineering_window: 5
feature_engineering_bb_window: 20

# Feature Selection Parameters
feature_selection:
  method: SelectKBest
  score_func: f_classif
  k: 50
  selected_features:
    - open
    - high
    - low
    - close
    - volume
    - quote_asset_volume
    - number_of_trades
    - taker_buy_base_volume
    - taker_buy_quote_volume
    - close_rolling_mean
    - volume_pct_change
    - close_bb_upper
    - close_bb_lower
    - close_rolling_std
    - volume_moving_avg

# Training Parameters
num_trials: 200  # Number of Optuna trials for hyperparameter tuning

# Ensemble Parameters
ensemble_method: stacking  # Options: 'equal', 'performance', 'stacking'
optimize_window: false

# Model Performance Metrics (for weighting schemes)
model_metrics:
  xgb_f1: 0.5231  # Replace with actual validation F1 Score for XGBoost
  lstm_f1: 0.5186  # Replace with actual validation F1 Score for LSTM

# Model Paths
model_paths:
  xgb_model_path: "results/models/xgb_best_model.json"
  lstm_model_path: "results/models/lstm_multistep_optuna.pth"
  meta_model_path: "results/models/stacking_meta_model_final_rf.pkl"

# Data Paths
data_paths:
  train_data_path: "/Users/mchildress/Code/my_crypto_prediction/data/intermediate/train_fe.csv"
  val_data_path: "/Users/mchildress/Code/my_crypto_prediction/data/intermediate/val_fe.csv"
  test_data_path: "/Users/mchildress/Code/my_crypto_prediction/data/final/test_fe.csv"
  train_features_path: "/Users/mchildress/Code/my_crypto_prediction/data/intermediate/train_features.csv"
  sample_submission_path: "/Users/mchildress/Code/my_crypto_prediction/data/raw/sample_submission.csv"

# Stacking Meta-learner Parameters
stacking_meta_learner:
  model_type: "rf"  # Options: 'xgb', 'lr', 'rf'
  n_splits: 5
  n_jobs: 8

# LSTM Parameters
lstm:
  window_size: 5
  batch_size: 128
  hidden_dim: 256
  num_layers: 2
  dropout: 0.3
  bidirectional: True
  learning_rate: 0.001

# Submission Parameters
submission:
  id_column: "row_id"  
  target_column: "target"  
  xgb_output_submission_path: "/Users/mchildress/Code/my_crypto_prediction/results/xgb_submission.csv"
  lstm_output_submission_path: "/Users/mchildress/Code/my_crypto_prediction/results/lstm_submission.csv"
  combined_output_submission_path: "/Users/mchildress/Code/my_crypto_prediction/results/combined_submission.csv"